# -*- coding: utf-8 -*-
"""FinalANNK3Bismillah.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wpyveet_20fw6tcS_olS-ihv0A7gDROa
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import glob
import re
import warnings
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

warnings.filterwarnings('ignore')

print("--- TAHAP 1: INTEGRASI DATA & HEATMAP PCA LOADINGS (PC1-PC5) ---")

all_files = glob.glob("*.xlsx")

if len(all_files) == 0:
    print("⚠️ ERROR: Belum ada file Excel! Upload dulu.")
else:
    # 1. Radar Pintar Deteksi Kolom
    pola_kolom = {
        'Accessibility': r'^(ACC|EOA|ACB)\d+$',
        'Customer_Support': r'^(CS|CST|CSP|CSS)\d+$',
        'Security': r'^(SC|SCR|SEC)\d+$',
        'Perceived_Usefulness': r'^(PU|PUS|PUF|PCU)\d+$',
        'Perceived_Ease_of_Use': r'^(PEU|PEOU)\d+$',
        'Subjective_Norm': r'^(SN|SBN|SNR|SJN)\d+$',
        'Perceived_Behavioral_Control': r'^(PBC)\d+$',
        'Behavioral_Intention': r'^(BI|BIN|BHI)\d+$'
    }

    data_bersih_gabungan = []
    for f in all_files:
        df_mentah = pd.read_excel(f)
        df_matang = pd.DataFrame()
        for konstruk, pola in pola_kolom.items():
            kolom_cocok = [col for col in df_mentah.columns if re.match(pola, col)]
            if kolom_cocok:
                df_matang[konstruk] = df_mentah[kolom_cocok].mean(axis=1)

        kolom_angka = df_mentah.select_dtypes(include=[np.number]).columns
        if len(kolom_angka) > 0:
            mask_rajin = df_mentah[kolom_angka].std(axis=1) > 0
            df_matang = df_matang[mask_rajin]
        data_bersih_gabungan.append(df_matang)

    df_var = pd.concat(data_bersih_gabungan, ignore_index=True)

    # 2. Standarisasi & Hitung PCA (Dibatasi 5 Komponen saja)
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(df_var)

    # DISINI KUNCINYA: Kita set n_components=5
    pca = PCA(n_components=5, random_state=42)
    pca.fit(X_scaled)
    pca_res = pca.transform(X_scaled)

    # Membuat tabel Loadings dengan kolom PC1 sampai PC5
    column_names = [f'PC{i+1}' for i in range(5)]
    loadings = pd.DataFrame(
        pca.components_.T,
        columns=column_names,
        index=df_var.columns
    )

    # 3. Visualisasi Heatmap PCA Loadings (Persis gaya Dosen)
    plt.figure(figsize=(10, 8))
    sns.heatmap(loadings, annot=True, cmap='coolwarm', fmt='.2f', center=0, vmin=-1, vmax=1)
    plt.title('Heatmap PCA Loadings (Limited to PC1-PC5)', fontsize=14)
    plt.ylabel('Original Features')
    plt.xlabel('Principal Components')
    plt.show()

    print(f"✅ Berhasil! Sekarang kolomnya sudah pas sampai PC5.")

from sklearn.cluster import KMeans
from sklearn.metrics import davies_bouldin_score, calinski_harabasz_score, silhouette_score
from sklearn.metrics.pairwise import euclidean_distances
import numpy as np
import pandas as pd

print("--- 2. ANALISIS PENENTUAN JUMLAH KLASTER OPTIMAL ---")

# Fungsi hitung Dunn Index (Metrik tambahan biar skripsi makin kuat)
def calculate_dunn_index(X, labels):
    unique_labels = np.unique(labels)
    max_intra = 0
    for label in unique_labels:
        cluster_points = X[labels == label]
        if len(cluster_points) > 1:
            intra_dist = np.max(euclidean_distances(cluster_points))
            max_intra = max(max_intra, intra_dist)
    min_inter = np.inf
    for i in range(len(unique_labels)):
        for j in range(i + 1, len(unique_labels)):
            inter_dist = np.min(euclidean_distances(X[labels == unique_labels[i]], X[labels == unique_labels[j]]))
            min_inter = min(min_inter, inter_dist)
    return min_inter / max_intra if max_intra > 0 else 0

eval_results = []
# Kita uji dari K=2 sampai K=6
for k in range(2, 7):
    km = KMeans(n_clusters=k, init='k-means++', n_init=10, random_state=42)
    lab = km.fit_predict(X_scaled)
    eval_results.append({
        'k': k,
        'Silhouette Score': silhouette_score(X_scaled, lab),
        'DBI (Semakin Kecil Semakin Bagus)': davies_bouldin_score(X_scaled, lab),
        'CH Index': calinski_harabasz_score(X_scaled, lab),
        'Dunn Index': calculate_dunn_index(X_scaled, lab)
    })

df_eval = pd.DataFrame(eval_results)

# 1. Tampilkan tabel perbandingan metrik
print("Tabel Evaluasi K-Means++:")
print(df_eval.to_string(index=False))
print("-" * 60)

# 2. SISTEM OTOMATIS MEMILIH K TERBAIK
# Kita pakai Silhouette Score sebagai acuan utama
best_k = int(df_eval.loc[df_eval['Silhouette Score'].idxmax()]['k'])

print(f"\nKesimpulan Mesin:")
print(f"Berdasarkan nilai Silhouette Score tertinggi, jumlah klaster optimal adalah: K = {best_k}")

# 3. EKSEKUSI FINAL CLUSTERING
kmeans_final = KMeans(n_clusters=best_k, init='k-means++', n_init=10, random_state=42)
df_var['Cluster'] = kmeans_final.fit_predict(X_scaled)

print(f"✅ Klasterisasi selesai. Data responden kini telah dikelompokkan ke {best_k} Cluster.")

import matplotlib.pyplot as plt
import seaborn as sns

print("--- 3. VISUALISASI SEBARAN KLASTER (PCA) ---")

# 1. Menyiapkan data visualisasi (PC1 dan PC2 dari Sel 1 tadi)
# Kita ambil pca_res yang sudah berisi koordinat 2 dimensi
plt.figure(figsize=(10, 7))

# 2. Plotting menggunakan Seaborn
sns.scatterplot(
    x=pca_res[:, 0],
    y=pca_res[:, 1],
    hue=df_var['Cluster'],
    palette='viridis',
    s=60,
    alpha=0.7,
    edgecolor='w'
)

plt.title('Visualisasi Sebaran Responden Berdasarkan 3 Klaster', fontsize=14)
plt.xlabel('Principal Component 1 (PC1)')
plt.ylabel('Principal Component 2 (PC2)')
plt.legend(title='Cluster ID', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.grid(True, linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

# 3. Menghitung jumlah orang per kelompok
counts = df_var['Cluster'].value_counts().sort_index()
print("\nDistribusi Jumlah Responden per Klaster:")
for i, count in counts.items():
    persen = (count / len(df_var)) * 100
    print(f"• Cluster {i}: {count} responden ({persen:.2f}%)")

print("--- 4. PROFILING KLASTER & PEMBERIAN LABEL ---")

# 1. Hitung rata-rata tiap variabel per klaster
tabel_profil = df_var.groupby('Cluster').mean()

# 2. Urutkan berdasarkan Behavioral Intention (BI) untuk menentukan Low, Moderate, High
# Kita cari urutan index dari BI yang terkecil ke terbesar
urutan_bi = tabel_profil['Behavioral_Intention'].sort_values().index

# Mapping otomatis berdasarkan urutan nilai rata-rata
# Nilai terkecil = Low, Tengah = Moderate, Tertinggi = High
label_map = {
    urutan_bi[0]: 'BI-Low',
    urutan_bi[1]: 'BI-Moderate',
    urutan_bi[2]: 'BI-High'
}

kesimpulan_map = {
    urutan_bi[0]: 'Rendah',
    urutan_bi[1]: 'Menengah',
    urutan_bi[2]: 'Tinggi'
}

# Terapkan label ke dataframe utama
df_var['Label'] = df_var['Cluster'].map(label_map)

# 3. Tampilkan Tabel Profiling untuk Bahan Skripsi
print("\nTabel Rata-Rata (Mean) per Klaster:")
print(tabel_profil.round(2).to_string())
print("\n" + "="*50)

# 4. Tampilkan Tabel Ringkasan Label
summary_label = []
for c in range(3):
    summary_label.append({
        'Cluster ID': c,
        'Pseudo Label': label_map[c],
        'Mean BI': tabel_profil.loc[c, 'Behavioral_Intention'],
        'Tingkat Adopsi': kesimpulan_map[c]
    })

df_summary = pd.DataFrame(summary_label)
print("\nRingkasan Penamaan Label:")
print(df_summary.to_string(index=False))

print(f"\n✅ Labelisasi selesai. Sekarang kamu punya target 'Label' untuk diolah di Machine Learning!")

from sklearn.model_selection import train_test_split
from sklearn.feature_selection import RFE
from sklearn.svm import SVC
from imblearn.over_sampling import SMOTE
from sklearn.preprocessing import StandardScaler

print("--- 5. PERSIAPAN DATA MACHINE LEARNING (SMOTE & RFE) ---")

# 1. Menentukan Fitur (X) dan Target (y)
X = df_var.drop(columns=['Cluster', 'Label'])
y = df_var['Label']

# 2. Split Data (80% Latih, 20% Uji)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# 3. Scaling Data (Wajib untuk SVM dan ANN)
scaler_ml = StandardScaler()
X_train_scaled = scaler_ml.fit_transform(X_train)
X_test_scaled = scaler_ml.transform(X_test)

# 4. SMOTE (Menyeimbangkan jumlah sampel tiap label)
# Kita pakai k_neighbors=5 sesuai standar
smote = SMOTE(k_neighbors=5, random_state=42)
X_train_res, y_train_res = smote.fit_resample(X_train_scaled, y_train)

print(f"Jumlah data setelah SMOTE:")
print(y_train_res.value_counts())

# 5. RFE (Feature Selection) menggunakan SVM Linear
# Memilih fitur terbaik secara otomatis
estimator = SVC(kernel="linear", random_state=42)
selector = RFE(estimator, n_features_to_select=None, step=1)
selector = selector.fit(X_train_res, y_train_res)

# Ambil data yang sudah diseleksi fiturnya
X_train_rfe = X_train_res[:, selector.support_]
X_test_rfe = X_test_scaled[:, selector.support_]

num_features = X_train_rfe.shape[1]
fitur_terpilih = X.columns[selector.support_].tolist()

print(f"\n✅ Seleksi Fitur Selesai!")
print(f"Jumlah Fitur Terbaik: {num_features}")
print(f"Fitur yang digunakan: {fitur_terpilih}")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

if 'trained_models' not in globals():
    trained_models = {}

print(f"{'='*30} Logistic Regression (LogR) {'='*30}")
print("Nilai k (k_neighbors) yang digunakan oleh SMOTE: 5")

try:
    # Cek apakah variabel num_features ada, kalau tidak, abaikan print-nya
    if 'num_features' in globals():
        print(f"jumlah feature terbaik: {num_features}")

    model_logr = LogisticRegression(C=10, penalty='l2', max_iter=1000, random_state=42)
    model_logr.fit(X_train_rfe, y_train_res)
    cv_scores = cross_val_score(model_logr, X_train_rfe, y_train_res, cv=5, scoring='f1_macro')
    y_pred = model_logr.predict(X_test_rfe)
    trained_models["Logistic Regression"] = model_logr

    print("\n=== F1-Score per Fold dari 5-fold Cross Validation ===")
    df_cv = pd.DataFrame(cv_scores, columns=['F1-Score'])
    print(df_cv)
    df_cv.to_csv('LogR_SMOTE_5_fold_CV_RFE_SVM_Linear_BI.csv', index=False)

    print(f"\n=== Hasil Klasifikasi: Logistic Regression ===")
    print(f"Accuracy: {accuracy_score(y_test, y_pred):.4f}")
    print(classification_report(y_test, y_pred))

    plt.figure(figsize=(6,4))
    sns.heatmap(confusion_matrix(y_test, y_pred), annot=True, fmt='d', cmap='YlGnBu',
                xticklabels=np.unique(y_test), yticklabels=np.unique(y_test))
    plt.title("Confusion Matrix: Logistic Regression")
    plt.ylabel('Actual')
    plt.xlabel('Predicted')
    plt.show()

except NameError:
    print("\n❌ STOP: Data belum siap! Jalankan dulu sel SMOTE & RFE di atas ya.")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

if 'trained_models' not in globals():
    trained_models = {}

print(f"{'='*30} Random Forest (RF) {'='*30}")
print("Nilai k (k_neighbors) yang digunakan oleh SMOTE: 5")

try:
    model_rf = RandomForestClassifier(max_depth=5, min_samples_leaf=10, n_estimators=100, random_state=42)
    model_rf.fit(X_train_rfe, y_train_res)
    cv_scores = cross_val_score(model_rf, X_train_rfe, y_train_res, cv=5, scoring='f1_macro')
    y_pred = model_rf.predict(X_test_rfe)
    trained_models["Random Forest"] = model_rf

    print("\n=== F1-Score per Fold dari 5-fold Cross Validation ===")
    df_cv = pd.DataFrame(cv_scores, columns=['F1-Score'])
    print(df_cv)
    df_cv.to_csv('RF_SMOTE_5_fold_CV_RFE_SVM_Linear_BI.csv', index=False)

    print(f"\n=== Hasil Klasifikasi: Random Forest ===")
    print(f"Accuracy: {accuracy_score(y_test, y_pred):.4f}")
    print(classification_report(y_test, y_pred))

    plt.figure(figsize=(6,4))
    sns.heatmap(confusion_matrix(y_test, y_pred), annot=True, fmt='d', cmap='Greens',
                xticklabels=np.unique(y_test), yticklabels=np.unique(y_test))
    plt.title("Confusion Matrix: Random Forest")
    plt.ylabel('Actual')
    plt.xlabel('Predicted')
    plt.show()

except NameError:
    print("\n❌ STOP: Data belum siap! Jalankan dulu sel SMOTE & RFE di atas ya.")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

if 'trained_models' not in globals():
    trained_models = {}

print(f"{'='*30} Gradient Boosting (GB) {'='*30}")
print("Nilai k (k_neighbors) yang digunakan oleh SMOTE: 5")

try:
    model_gb = GradientBoostingClassifier(max_depth=3, n_estimators=50, learning_rate=0.1, random_state=42)
    model_gb.fit(X_train_rfe, y_train_res)
    cv_scores = cross_val_score(model_gb, X_train_rfe, y_train_res, cv=5, scoring='f1_macro')
    y_pred = model_gb.predict(X_test_rfe)
    trained_models["Gradient Boosting"] = model_gb

    print("\n=== F1-Score per Fold dari 5-fold Cross Validation ===")
    df_cv = pd.DataFrame(cv_scores, columns=['F1-Score'])
    print(df_cv)
    df_cv.to_csv('GB_SMOTE_5_fold_CV_RFE_SVM_Linear_BI.csv', index=False)

    print(f"\n=== Hasil Klasifikasi: Gradient Boosting ===")
    print(f"Accuracy: {accuracy_score(y_test, y_pred):.4f}")
    print(classification_report(y_test, y_pred))

    plt.figure(figsize=(6,4))
    sns.heatmap(confusion_matrix(y_test, y_pred), annot=True, fmt='d', cmap='Oranges',
                xticklabels=np.unique(y_test), yticklabels=np.unique(y_test))
    plt.title("Confusion Matrix: Gradient Boosting")
    plt.ylabel('Actual')
    plt.xlabel('Predicted')
    plt.show()

except NameError:
    print("\n❌ STOP: Data belum siap! Jalankan dulu sel SMOTE & RFE di atas ya.")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

if 'trained_models' not in globals():
    trained_models = {}

print(f"{'='*30} Artificial Neural Network (ANN) {'='*30}")
print("Nilai k (k_neighbors) yang digunakan oleh SMOTE: 5")

try:
    model_ann = MLPClassifier(hidden_layer_sizes=(32, 16), max_iter=500, random_state=42)
    model_ann.fit(X_train_rfe, y_train_res)
    cv_scores = cross_val_score(model_ann, X_train_rfe, y_train_res, cv=5, scoring='f1_macro')
    y_pred = model_ann.predict(X_test_rfe)
    trained_models["ANN"] = model_ann

    print("\n=== F1-Score per Fold dari 5-fold Cross Validation ===")
    df_cv = pd.DataFrame(cv_scores, columns=['F1-Score'])
    print(df_cv)
    df_cv.to_csv('ANN_SMOTE_5_fold_CV_RFE_SVM_Linear_BI.csv', index=False)

    print(f"\n=== Hasil Klasifikasi: ANN ===")
    print(f"Accuracy: {accuracy_score(y_test, y_pred):.4f}")
    print(classification_report(y_test, y_pred))

    plt.figure(figsize=(6,4))
    sns.heatmap(confusion_matrix(y_test, y_pred), annot=True, fmt='d', cmap='Reds',
                xticklabels=np.unique(y_test), yticklabels=np.unique(y_test))
    plt.title("Confusion Matrix: ANN")
    plt.ylabel('Actual')
    plt.xlabel('Predicted')
    plt.show()

except NameError:
    print("\n❌ STOP: Data belum siap! Jalankan dulu sel SMOTE & RFE di atas ya.")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.svm import SVC
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

if 'trained_models' not in globals():
    trained_models = {}

print(f"{'='*30} Support Vector Machine (SVM) {'='*30}")
print("Nilai k (k_neighbors) yang digunakan oleh SMOTE: 5")

try:
    model_svm = SVC(kernel='rbf', probability=True, random_state=42)
    model_svm.fit(X_train_rfe, y_train_res)
    cv_scores = cross_val_score(model_svm, X_train_rfe, y_train_res, cv=5, scoring='f1_macro')
    y_pred = model_svm.predict(X_test_rfe)
    trained_models["SVM"] = model_svm

    print("\n=== F1-Score per Fold dari 5-fold Cross Validation ===")
    df_cv = pd.DataFrame(cv_scores, columns=['F1-Score'])
    print(df_cv)
    df_cv.to_csv('SVM_SMOTE_5_fold_CV_RFE_SVM_Linear_BI.csv', index=False)

    print(f"\n=== Hasil Klasifikasi: SVM ===")
    print(f"Accuracy: {accuracy_score(y_test, y_pred):.4f}")
    print(classification_report(y_test, y_pred))

    plt.figure(figsize=(6,4))
    sns.heatmap(confusion_matrix(y_test, y_pred), annot=True, fmt='d', cmap='Purples',
                xticklabels=np.unique(y_test), yticklabels=np.unique(y_test))
    plt.title("Confusion Matrix: SVM")
    plt.ylabel('Actual')
    plt.xlabel('Predicted')
    plt.show()

except NameError:
    print("\n❌ STOP: Data belum siap! Jalankan dulu sel SMOTE & RFE di atas ya.")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from xgboost import XGBClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

if 'trained_models' not in globals():
    trained_models = {}

print(f"{'='*30} XGBoost {'='*30}")
print("Nilai k (k_neighbors) yang digunakan oleh SMOTE: 5")

try:
    # Encode target labels to numerical values for XGBoost
    le = LabelEncoder()
    y_train_xgb = le.fit_transform(y_train_res)
    y_test_xgb = le.transform(y_test)

    # XGBoost menggunakan y_train_xgb & y_test_xgb yang sudah di-encode angka
    model_xgb = XGBClassifier(max_depth=3, n_estimators=100, learning_rate=0.1, random_state=42)
    model_xgb.fit(X_train_rfe, y_train_xgb)
    cv_scores = cross_val_score(model_xgb, X_train_rfe, y_train_xgb, cv=5, scoring='f1_macro')
    y_pred_num = model_xgb.predict(X_test_rfe)
    y_pred = le.inverse_transform(y_pred_num)
    trained_models["XGBoost"] = model_xgb

    print("\n=== F1-Score per Fold dari 5-fold Cross Validation ===")
    df_cv = pd.DataFrame(cv_scores, columns=['F1-Score'])
    print(df_cv)
    df_cv.to_csv('XGBoost_SMOTE_5_fold_CV_RFE_SVM_Linear_BI.csv', index=False)

    print(f"\n=== Hasil Klasifikasi: XGBoost ===")
    print(f"Accuracy: {accuracy_score(y_test, y_pred):.4f}")
    print(classification_report(y_test, y_pred))

    plt.figure(figsize=(6,4))
    sns.heatmap(confusion_matrix(y_test, y_pred), annot=True, fmt='d', cmap='YlOrBr',
                xticklabels=le.classes_, yticklabels=le.classes_)
    plt.title("Confusion Matrix: XGBoost")
    plt.ylabel('Actual')
    plt.xlabel('Predicted')
    plt.show()

except NameError:
    print("\n❌ STOP: Data belum siap! Jalankan dulu sel SMOTE & RFE di atas ya.")

import pandas as pd

print(f"{'='*20} 12. FINAL OVERFITTING TEST {'='*20}")
print("Metode: Perbandingan Akurasi Training vs Testing (Toleransi Gap <= 5%)\n")

try:
    # Sabuk Pengaman 1: Cek apakah keranjang model sudah ada isinya
    if 'trained_models' not in globals() or len(trained_models) == 0:
        print("⚠️ Eits, keranjang 'trained_models' masih kosong!")
        print("💡 Jalankan dulu minimal satu sel algoritma (LogR/RF/ANN/dll) di atas ya.")
    else:
        results_overfit = []

        # Looping untuk mengecek semua model yang sudah dilatih
        for name, model in trained_models.items():

            # 1. Hitung Akurasi Training (Data yang sudah di-SMOTE)
            if name == "XGBoost":
                # XGBoost butuh data yang di-encode angka
                train_acc = model.score(X_train_rfe, y_train_xgb)
                test_acc = model.score(X_test_rfe, y_test_xgb)
            else:
                train_acc = model.score(X_train_rfe, y_train_res)
                test_acc = model.score(X_test_rfe, y_test)

            # 2. Hitung Selisih (Gap)
            gap = abs(train_acc - test_acc)

            # 3. Tentukan Status (Jika Gap di bawah 0.05 atau 5%, maka Aman)
            status = '✅ Aman' if gap <= 0.05 else '⚠️ Overfit'

            results_overfit.append({
                'Model': name,
                'Train Acc': f"{train_acc*100:.2f}%",
                'Test Acc': f"{test_acc*100:.2f}%",
                'Gap': f"{gap*100:.2f}%",
                'Status': status
            })

        # Tampilkan tabel hasil akhir
        df_final_test = pd.DataFrame(results_overfit)
        print(df_final_test.to_string(index=False))

        # Simpan hasil evaluasi ke CSV untuk lampiran skripsi
        df_final_test.to_csv('Hasil_Final_Overfitting_Semua_Algoritma.csv', index=False)
        print("\n✅ Tabel hasil overfitting telah disimpan sebagai 'Hasil_Final_Overfitting_Semua_Algoritma.csv'")

except NameError as e:
    print(f"\n❌ STOP: Ada data yang belum siap! Pesan error: {e}")
    print("💡 Pastikan kamu sudah me-run sel data (SMOTE/RFE) dan sel XGBoost (jika ingin mengecek XGBoost).")

import pandas as pd
from sklearn.model_selection import cross_val_score

print(f"{'='*20} 13. EXPORT HASIL KE CSV {'='*20}")
print("Memproses pembuatan file CSV untuk lampiran skripsi...\n")

try:
    # Sabuk Pengaman: Cek diam-diam apakah variabel penting sudah di-run
    _ = selector
    _ = trained_models
    _ = X_train_rfe

    # 1. Membuat file Ranking Fitur RFE (Gunakan X_train sebagai referensi kolom)
    df_ranking = pd.DataFrame({
        'Fitur Asli': X.columns,
        'Ranking (1 = Terpilih)': selector.ranking_,
        'Status Terpilih': selector.support_
    })
    df_ranking.to_csv('Rangking_Fitur_SMOTE_RFE_SVM_BI.csv', index=False)
    print("✅ File Ranking Fitur RFE berhasil dibuat.")

    # 2. Membuat file Subset Data Terbaik (Konversi dari Numpy ke DataFrame dulu)
    df_subset = pd.DataFrame(X_train_rfe, columns=fitur_terpilih)
    df_subset.to_csv('Subset_SMOTE_RFE_SVM_Linear_BI.csv', index=False)
    print("✅ File Subset Data Terbaik berhasil dibuat.")

    # 3. Membuat file 5-Fold CV F1-Score untuk SEMUA Algoritma
    for name, model in trained_models.items():
        if name == "XGBoost":
            cv_s = cross_val_score(model, X_train_rfe, y_train_xgb, cv=5, scoring='f1_macro')
            fname = "XGBoost"
        else:
            cv_s = cross_val_score(model, X_train_rfe, y_train_res, cv=5, scoring='f1_macro')
            if "Logistic" in name: fname = "LogR"
            elif "Random" in name: fname = "RF"
            elif "Gradient" in name: fname = "GB"
            elif "ANN" in name: fname = "ANN"
            elif "SVM" in name: fname = "SVM"
            else: fname = "Model"

        df_cv = pd.DataFrame(cv_s, columns=['F1-Score'])
        df_cv.to_csv(f'{fname}_SMOTE_5_fold_CV_RFE_SVM_Linear_BI.csv', index=False)
        print(f"✅ File CV untuk {name} berhasil dibuat.")

    print("\n🎉 SEMUA FILE CSV BERHASIL DIBUAT DENGAN AMAN!")
    print("Silakan cek di panel 'Files' (ikon folder) di sebelah kiri Colab kamu untuk mengunduhnya.")

except NameError as e:
    print(f"\n❌ STOP: Komputer lupa datamu! Pesan error: {e}")
    print("💡 CARA MENGATASI: Pastikan kamu sudah menjalankan sel RFE (yang ada 'selector') dan sel-sel model algoritma di atasnya.")

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import accuracy_score
import pandas as pd

# 1. AMBIL DATA AKURASI SECARA REAL-TIME DARI MEMORY LAPTOPMU
hasil_riil = []
for name, model in trained_models.items():
    y_p = model.predict(X_test_rfe)
    # Gunakan y_test_xgb khusus untuk XGBoost, sisanya pakai y_test asli
    target_y = y_test_xgb if name == "XGBoost" else y_test
    acc = accuracy_score(target_y, y_p) * 100
    hasil_riil.append({'Algoritma': name, 'Akurasi': acc})

# Urutkan secara otomatis: yang akurasi tertinggi akan berada di posisi paling atas di grafik
df_plot = pd.DataFrame(hasil_riil).sort_values(by='Akurasi', ascending=True)

# 2. VISUALISASI BERSIH & PROFESIONAL (BIAR GAK 'FREAK')
plt.figure(figsize=(12, 7))
sns.set_style("white") # Putih bersih tanpa garis-garis mengganggu

# Pakai palet warna gradasi yang elegan
colors = sns.color_palette("Blues_d", len(df_plot))

# Buat Bar Horizontal
bars = plt.barh(df_plot['Algoritma'], df_plot['Akurasi'], color=colors, height=0.7)

# Judul dan Label yang Jelas
plt.title('Peringkat Akurasi Model Prediksi Niat Adopsi Fintech\n(Hasil Komputasi Real-Time Environment Lokal)', 
          fontsize=15, weight='bold', pad=25)
plt.xlabel('Tingkat Akurasi (%)', fontsize=12, weight='600')

# Fokuskan skala agar perbedaan koma terlihat jelas
plt.xlim(min(df_plot['Akurasi']) - 1, 100)

# Tambahkan angka persentase di ujung batang secara otomatis
for bar in bars:
    width = bar.get_width()
    plt.text(width + 0.1, bar.get_y() + bar.get_height()/2, 
             f'{width:.2f}%', va='center', weight='bold', fontsize=11, color='#2c3e50')

# Hilangkan garis bingkai biar terlihat modern
sns.despine(left=True, bottom=False)
plt.tight_layout()

# Simpan untuk lampiran Bab 4
plt.savefig('Hasil_Akurasi_Asli_VSCode.png', dpi=300)
print("\n✅ GRAFIK SUDAH JADI! Cek file 'Hasil_Akurasi_Asli_VSCode.png'")

import pandas as pd
from sklearn.metrics import accuracy_score

# =========================================================
# EKSPOR DATA UNTUK DASHBOARD STREAMLIT
# =========================================================

# 1. Ekspor Data Dataset Matang (Pakai variabel df_var milikmu)
df_var.to_csv('data_dashboard.csv', index=False)

# 2. Ekspor Data Akurasi Model
hasil_akurasi_dashboard = []
for name, model in trained_models.items():
    # Hitung akurasi secara real-time dari model yang sudah di-train
    y_pred = model.predict(X_test_rfe)
    target_y = y_test_xgb if name == "XGBoost" else y_test
    acc = accuracy_score(target_y, y_pred) * 100
    hasil_akurasi_dashboard.append({'Algoritma': name, 'Akurasi': acc})

# Simpan ke CSV
pd.DataFrame(hasil_akurasi_dashboard).to_csv('model_results_dashboard.csv', index=False)

print("\n✅ DATA DASHBOARD BERHASIL DIEKSPOR!")